apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  DB_PASS: ZXhhbXBsZQ==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  DB_HOST: post-postgresql
  DB_USER: john
  DB: endgame

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunder-api
  labels:
    app.kubernetes.io/name: thunder-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: thunder-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thunder-api
    spec:
      containers:
        - name: thunder-api
          image: "prinsoo/thunderstorm:backend-v1"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                  name: api-configmap
            - secretRef:
                  name: api-secret
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: thunder-api
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: thunder-api