apiVersion: v1
kind: Secret
metadata:
  name: web-secret
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXM=
  REDIS_MASTER_PASSWORD: cmVkaXM=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-configmap
data:
  HOSTNAME: redis-master

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunder-web
  labels:
    app.kubernetes.io/name: thunder-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: thunder-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thunder-web
    spec:
      containers:
        - name: thunder-web
          image: "prinsoo/thunderstorm:frontend-v1"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                  name: web-configmap
            - secretRef:
                  name: web-secret
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: thunder-web
  labels:
    app.kubernetes.io/name: thunder-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: thunder-web