apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name }}-secret
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.env.REDIS_PASSWORD }}
  REDIS_MASTER_PASSWORD: {{ .Values.env.REDIS_MASTER_PASSWORD }}